### ISSUE TITLE
small_world_simulation; ModuleNotFoundError: No Module named 'networkx'

### ISSUE THREAD

**Issue by JohnSegerstedt** [JulianoLagana/spatial_pgg#3]
I get the above error on row 3 (import networkx as nx) of 'small_world_simulation.py', even after running the previous install command and also running 'pip install networkx'.

I realize now that I get an "You appear to be missing MuJuCo" error message during the install command. Not sure if these two are related...

**Comment by JulianoLagana** [comment]
MuJoCo? Wow, I probably screwed up the requirements file. I use MuJoCo for a different project, it should probably not be here at all. I'll look into it.

**Comment by JulianoLagana** [comment]
I have now removed unused packages from `requirements.txt` (7d7f2156b1aa24bf90554bf50fec109cd7e31836) that were there because I made a mistake when trying to create an empty conda env for the requirements file.

@JohnSegerstedt could you try installing again and see if you still get the problem? And it's also nice if you can be on the lookout for any errors during the installation too.

**Comment by JohnSegerstedt** [comment]
I will try the new installation commands out after the meeting today.
